### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by lenamtl** [bigbhowell/Photopile-JS#4]
Is there a way to use it with IE9?

**Comment by bigbhowell** [comment]
PhotopileJS is just a *for fun* project, and because of this I developed it with limited cross-browser compatibility testing. This is especially the case for older versions of IE, thus it currently does not support <IE10. Unfortunately I am unable to devout any time to PhotopileJS in order to make the adjustments needed. If you are interested, I encourage you to contribute to the project to add support for <IE10. On IE9 the gallery is not loading, so the init function is a good place to start. Just taking a quick glance at the code I'd likely begin by looking at `$(window).load(function() ... ` on line 57.
